### ISSUE TITLE
我成功安装好扩展，想预览出现不了编辑器界面～

### ISSUE THREAD

**Issue by hyrbridword** [douyasi/laravel-editor-md#1]
![image](https://cloud.githubusercontent.com/assets/19897885/20201569/10c5abcc-a7f4-11e6-93d8-b384c1d4713e.png)

**Comment by ycrao** [comment]
我需要更多的细节信息，比如操作系统、Laravel版本等。

**Comment by hyrbridword** [comment]
我是阿里云上面的，ubuntu14.04.laravel版本是5.2.45,

**Comment by ycrao** [comment]
@ChenPHPER 浏览器f12看看console栏有没有爆js之类错误

**Comment by MonKing0601** [comment]
跟他一样的情况，
爆JS的错误了。
http://localhost:8080/vendor/editor.md/lib/marked.min.js 
全都这种错误
缺少了项目名称的路径，应该是 
http://localhost:8080/laravel/public/vendor/editor.md/lib/marked.min.js吧。

**Comment by ycrao** [comment]
@MonKing0601 请参考安装说明, `Laravel` 默认绑定的是 public 目录,你绑定的是项目根目录,自然路径不对.
