### ISSUE TITLE
emoji图片目录错误

### ISSUE THREAD

**Issue by sucof** [douyasi/laravel-editor-md#2]
项目用的是http://www.emoji-cheat-sheet.com/graphics/emojis/bowtie.png 目录，现在已经不对，现在为 https://www.webpagefx.com/tools/emoji-cheat-sheet/graphics/emojis/bowtie.png ，需要重新配置下 emoji目录为 https://www.webpagefx.com/tools/emoji-cheat-sheet/

**Comment by ycrao** [comment]
@sucof 
`editor.md` 官方似乎没有更新路径，但是使用本人的包，已经重载 `emoji` 路径，不存在这问题。请使用本插件提供的 `helper` 方法生成相关js代码。
https://github.com/douyasi/laravel-editor-md/blob/master/src/helpers.php#L79-L83
![image](https://cloud.githubusercontent.com/assets/3280204/26277018/45aae908-3db6-11e7-8326-559b6b9600e0.png)

![image](https://cloud.githubusercontent.com/assets/3280204/26277013/29d1ec72-3db6-11e7-88de-2e6129b8a5b2.png)
